#!/bin/sh

PLAY=
DOWN_DIR=
URL=

while [ -n "$1" ]
do
    case "$1" in 
        -p|--play)
            PLAY=1
            ;;
        -d|--download)
            shift
            case "$1" in
                ~*)echo "$1";;
                -*|"")
                    echo provide a directory
                    exit 1
                    ;;
                *)
                    DOWN_DIR="$1"
                    ;;
            esac
            ;;
        -*)
            echo "not an option $1"
            exit 1
            ;;
        *)
            URL="$1"
            echo $URL
            ;;
    esac
    shift
done
echo DD: $DOWN_DIR

